# Generated by Django 6.0.6 on 2026-06-28 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="completed_units",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_semester",
            field=models.CharField(default="Fall", max_length=24),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.CharField(max_length=24, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("credits", models.PositiveSmallIntegerField(default=3)),
                ("semester", models.CharField(default="Fall", max_length=24)),
                ("category", models.CharField(default="General", max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("prerequisites", models.ManyToManyField(blank=True, to="api.unit")),
            ],
        ),
        migrations.CreateModel(
            name="StudentUnitEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("waitlist", "Waitlisted"),
                        ],
                        default="enrolled",
                        max_length=16,
                    ),
                ),
                ("semester", models.CharField(default="Fall", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="api.studentprofile",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="api.unit",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "unit")},
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="api.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="enrolled_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="api.StudentUnitEnrollment",
                to="api.unit",
            ),
        ),
    ]
