# Generated by Django 6.0.6 on 2026-06-29 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_assignment_activity_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsession",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="api.unitsection",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="api.course",
            ),
        ),
    ]
