# Generated by Django 6.0.6 on 2026-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_classsession_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('project', 'Project')], default='assignment', max_length=24),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
