from django.urls import path

from .views import (
    academic_risk,
    api_status,
    chatbot,
    choose_classes,
    events,
    knowledge_search,
    me,
    recommendations,
    sentiment,
    students,
    timetable,
    units,
    assignments_api,
    unit_recommendations,
    enroll_unit,
    drop_unit,
    # UI views

    ai_recommendations_ui,
    academic_analytics_ui,
    knowledge_search_ui,
    events_ui,
    my_profile_ui,
    my_courses_ui,
    ai_assistant_ui,
    settings_ui,
    admin_dashboard,
    admin_grade_student_api,
    admin_grade_item_api,
    admin_add_assignment_api,
    admin_add_event_api,
    admin_overview_api,
    api_logout,
    api_login,
    api_register,
)

urlpatterns = [
    path("status/", api_status, name="api-status"),
    path("students/", students, name="students"),
    path("recommendations/", recommendations, name="recommendations"),
    path("risk/", academic_risk, name="academic-risk"),
    path("knowledge-search/", knowledge_search, name="knowledge-search"),
    path("sentiment/", sentiment, name="sentiment"),
    path("chatbot/", chatbot, name="chatbot"),
    path("choose-classes/", choose_classes, name="choose_classes"),
    # UI pages (server-rendered shells calling API endpoints)
    path("ai-recommendations/", ai_recommendations_ui, name="ai_recommendations_ui"),
    path("academic-analytics/", academic_analytics_ui, name="academic_analytics_ui"),
    path("knowledge-search-ui/", knowledge_search_ui, name="knowledge_search_ui"),
    path("events-ui/", events_ui, name="events_ui"),
    path("my-profile/", my_profile_ui, name="my_profile_ui"),
    path("my-courses/", my_courses_ui, name="my_courses_ui"),
    path("ai-assistant-ui/", ai_assistant_ui, name="ai_assistant_ui"),
    path("settings-ui/", settings_ui, name="settings_ui"),
    path("me/", me, name="api-me"),
    path("events/", events, name="api-events"),
    path("assignments/", assignments_api, name="api-assignments"),
    path("timetable/", timetable, name="api-timetable"),
    path("units/", units, name="api-units"),
    path("units/recommendations/", unit_recommendations, name="api-unit-recommendations"),
    path("units/enroll/", enroll_unit, name="api-unit-enroll"),
    path("units/drop/", drop_unit, name="api-unit-drop"),

    path("admin-dashboard/", admin_dashboard, name="admin_dashboard"),
    path("admin/overview/", admin_overview_api, name="admin-overview-api"),
    path("admin/grade-student/", admin_grade_student_api, name="admin-grade-student-api"),
    path("admin/grade-item/", admin_grade_item_api, name="admin-grade-item-api"),
    path("admin/add-assignment/", admin_add_assignment_api, name="admin-add-assignment-api"),
    path("admin/add-event/", admin_add_event_api, name="admin-add-event-api"),
    path("auth/logout/", api_logout, name="api-logout"),
    path("auth/login/", api_login, name="api-login"),
    path("auth/register/", api_register, name="api-register"),
]

